### ISSUE TITLE
dot not work ? 

### ISSUE THREAD

**Issue by OmiChrome** [57op/simple-mpv-webui-windows-libs#5]
i tried the way as readme.md says . but not worked for me 

i put everything in mpv-installtion folder :(

please tell how to do ?

**Comment by 57op** [comment]
Hello,
sad to know it's not working for you.

Are you trying to compile or just to install pre-built libraries?
Which build of mpv are you using? Is it recent? (e.g. latest from shinchiro)

**Comment by OmiChrome** [comment]
> Hello, sad to know it's not working for you.
> 
> Are you trying to compile or just to install pre-built libraries? Which build of mpv are you using? Is it recent? (e.g. latest from shinchiro)

prebuild binarys . idk  how to compile in window 

mpv -version 
![image](https://user-images.githubusercontent.com/108952834/189985750-9851afad-f94a-4993-8f8f-b510b5e479fb.png)

**Comment by 57op** [comment]
Ok, thanks for reporting back!
I've seen that shinchiro enabled JIT for lua on x64 several days ago.

Can you try to download the artifact here: https://github.com/57op/simple-mpv-webui-windows-libs/actions/runs/3047636301 (release) and test?

**Comment by OmiChrome** [comment]
> Ok, thanks for reporting back! I've seen that shinchiro enabled JIT for lua on x64 several days ago.
> 
> Can you try to download the artifact here: https://github.com/57op/simple-mpv-webui-windows-libs/actions/runs/3047636301 (release) and test?

sure :O

**Comment by 57op** [comment]
I was finally able to test it my self!
New release available and it should be fixed, so I'm closing this.

Thanks for reporting

**Comment by OmiChrome** [comment]
omg omg omg 

😮   :O thsi does work . surely so fine  pog
