### ISSUE TITLE
mingw32-make appears to be trying to build in 64-bit, printing unsupported arch.

### ISSUE THREAD

**Issue by talzahr** [57op/simple-mpv-webui-windows-libs#6]
### _source build.sh_ build output:

> mingw32-make: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit'
> C:/MinGW/bin/mingw32-make -C src clean
> mingw32-make[1]: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit/src'
> rm -f luajit.exe libluajit.a lua51.dll host/minilua.exe host/buildvm.exe lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
> mingw32-make[1]: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit/src'
> mingw32-make: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit'
> mingw32-make: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit'
> ==== Building LuaJIT 2.1.0-beta3 ====
> C:/MinGW/bin/mingw32-make -C src
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> mingw32-make[1]: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit/src'
> mingw32-make[1]: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit/src'
> Makefile:274: *** Unsupported target architecture.  Stop.
> Makefile:112: recipe for target 'src/luajit' failed
> mingw32-make: *** [src/luajit] Error 2
> mingw32-make: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luajit'
> cp: cannot stat '/c/mpv-build/simple-mpv-webui-windows-libs/luajit/src/lua51.dll': No such file or directory
> mingw32-make: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket'
> C:/MinGW/bin/mingw32-make -C src clean
> mingw32-make[1]: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket/src'
> rm -f socket-3.0.0.so luasocket.o timeout.o buffer.o io.o auxiliar.o compat.o options.o inet.o usocket.o except.o select.o tcp.o udp.o buffer.o compat.o auxiliar.o options.o timeout.o io.o usocket.o serial.o
> rm -f mime-1.0.3.so unix.so serial.so mime.o compat.o buffer.o auxiliar.o options.o timeout.o io.o usocket.o unixstream.o unixdgram.o compat.o unix.o
> mingw32-make[1]: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket/src'
> mingw32-make: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket'
> mingw32-make: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket'
> C:/MinGW/bin/mingw32-make -C src mingw
> mingw32-make[1]: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket/src'
> C:/MinGW/bin/mingw32-make all PLAT=mingw
> mingw32-make[2]: Entering directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket/src'
> gcc  -IC:/mpv-build/simple-mpv-webui-windows-libs/luajit/out/include/luajit-2.1 -DWINVER=0x0602 -Wall -O2 -fno-common   -c -o luasocket.o luasocket.c
> In file included from luasocket.c:15:0:
> luasocket.h:27:17: fatal error: lua.h: No such file or directory
>  #include "lua.h"
>                  ^
> compilation terminated.
> <builtin>: recipe for target 'luasocket.o' failed
> mingw32-make[2]: *** [luasocket.o] Error 1
> mingw32-make[2]: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket/src'
> makefile:385: recipe for target 'mingw' failed
> mingw32-make[1]: *** [mingw] Error 2
> mingw32-make[1]: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket/src'
> makefile:18: recipe for target 'mingw' failed
> mingw32-make: *** [mingw] Error 2
> mingw32-make: Leaving directory 'C:/mpv-build/simple-mpv-webui-windows-libs/luasocket'
> '/c/mpv-build/simple-mpv-webui-windows-libs/luajit/COPYRIGHT' -> '/c/mpv-build/simple-mpv-webui-windows-libs/mpv/LUAJIT-LICENSE'
> '/c/mpv-build/simple-mpv-webui-windows-libs/luasocket/LICENSE' -> '/c/mpv-build/simple-mpv-webui-windows-libs/mpv/LUASOCKET-LICENSE'

### Environmental Vars

> $ env
> ProgramFiles(x86)=C:\Program Files (x86)
> !::=::\
> CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
> SHELL=/usr/bin/bash
> NUMBER_OF_PROCESSORS=16
> FPS_BROWSER_USER_PROFILE_STRING=Default
> PROCESSOR_LEVEL=23
> MSFS_SDK=C:\MSFS SDK\
> TERM_PROGRAM_VERSION=3.6.1
> MINGW_PREFIX=/mingw32
> CHROME_RESTART=Microsoft Edge|Microsoft Edge has stopped working. Restart it?|LEFT_TO_RIGHT
> PKG_CONFIG_PATH=/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig
> USERDOMAIN_ROAMINGPROFILE=DESKTOP-ADJLQ2K
> HOSTNAME=DESKTOP-ADJLQ2K
> EDGE_VARIATIONS_SEED_ETAG="ktOJkZcHHihq1+TXqGo2H+o4IHKF4Crors00I9nkImM="
> PROGRAMFILES=C:\Program Files (x86)
> MSYSTEM=MINGW32
> PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
> fscommunity=C:\Users\kroza\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community
> ORIGINAL_TEMP=/tmp
> MINGW_CHOST=i686-w64-mingw32
> OS=Windows_NT
> HOMEDRIVE=C:
> MSYSTEM_CARCH=i686
> USERDOMAIN=DESKTOP-ADJLQ2K
> PWD=/c/mpv-build/simple-mpv-webui-windows-libs
> USERPROFILE=C:\Users\kroza
> MANPATH=/mingw32/local/man:/mingw32/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man
> PROCESSOR_ARCHITEW6432=AMD64
> EDGE_METRICS_SESSION_ID=144
> MINGW_PACKAGE_PREFIX=mingw-w64-i686
> ALLUSERSPROFILE=C:\ProgramData
> ORIGINAL_PATH=/mingw32/bin:/usr/bin:/c/Users/kroza/bin:/c/Program Files (x86)/Microsoft/Edge/Application:/c/program files/oculus/support/oculus-runtime:/c/windows/system32:/c/windows:/c/windows/system32/wbem:/c/windows/system32/windowspowershell/v1.0:/c/windows/system32/openssh:/c/program files/nvidia corporation/nvidia nvdlisr:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Users/kroza/AppData/Local/Microsoft/WindowsApps
> CommonProgramW6432=C:\Program Files\Common Files
> HOME=/c/Users/kroza
> USERNAME=kroza
> SSH_ASKPASS=/mingw32/bin/git-askpass.exe
> PLINK_PROTOCOL=ssh
> OneDrive=C:\Users\kroza\OneDrive
> COMSPEC=C:\WINDOWS\system32\cmd.exe
> TMPDIR=/tmp
> APPDATA=C:\Users\kroza\AppData\Roaming
> SYSTEMROOT=C:\WINDOWS
> LOCALAPPDATA=C:\Users\kroza\AppData\Local
> COMPUTERNAME=DESKTOP-ADJLQ2K
> INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/share/info
> TERM=xterm
> LOGONSERVER=\\DESKTOP-ADJLQ2K
> ACLOCAL_PATH=/mingw32/share/aclocal:/usr/share/aclocal
> PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
> TEMP=/tmp
> MSYSTEM_CHOST=i686-w64-mingw32
> DISPLAY=needs-to-be-defined
> EDGE_UX_CONFIG_CORRELATION_ID=
> EDGE_USER_DATA_DIR=C:\Users\kroza\AppData\Local\Microsoft\Edge\User Data
> ORIGINAL_TMP=/tmp
> SHLVL=1
> PROCESSOR_REVISION=7100
> DriverData=C:\Windows\System32\Drivers\DriverData
> COMMONPROGRAMFILES=C:\Program Files (x86)\Common Files
> LC_CTYPE=en_US.UTF-8
> EXEPATH=C:\Program Files (x86)\Git
> PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
> SESSIONNAME=Console
> PS1=\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
> EDGE_METRICS_CLIENT_ID_HASH=3168565735762228980
> CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\LOCAL\crashpad_12012_GMIYSSPWFMBXTVWR
> HOMEPATH=\Users\kroza
> TMP=/tmp
> CONFIG_SITE=/etc/config.site
> PATH=/c/MinGW/:/c/MinGW/bin:/c/Users/kroza/bin:/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/mingw32/bin:/usr/bin:/c/Users/kroza/bin:/c/Program Files (x86)/Microsoft/Edge/Application:/c/program files/oculus/support/oculus-runtime:/c/windows/system32:/c/windows:/c/windows/system32/wbem:/c/windows/system32/windowspowershell/v1.0:/c/windows/system32/openssh:/c/program files/nvidia corporation/nvidia nvdlisr:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Users/kroza/AppData/Local/Microsoft/WindowsApps:/usr/bin/vendor_perl:/usr/bin/core_perl
> EDGE_BROWSER_PID=12012
> ProgramW6432=C:\Program Files
> MSYSTEM_PREFIX=/mingw32
> OculusBase=C:\Program Files\Oculus\
> WINDIR=C:\WINDOWS
> FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
> PROCESSOR_ARCHITECTURE=x86
> PUBLIC=C:\Users\Public
> SYSTEMDRIVE=C:
> OLDPWD=/c/mpv-build
> TERM_PROGRAM=mintty
> ProgramData=C:\ProgramData
> _=/usr/bin/env

### Git version
>git version 2.38.0.windows.1

### mingw32-make.exe --version
>GNU Make 3.82.90
>Built for i686-pc-mingw32
>...

Tried Git 64bit (/w Git Bash) and uninstalled and used Git 32bit. PATH env was fine and was able to see git and MinGW32 binaries from build location. I'm not as proficient with Windows 10 as GNU/Linux. So, I'm probably just missing something stupidly obvious here.

*edit: codeblock broke formatting.

**Comment by talzahr** [comment]
Like I said, something obvious... I saw there's a prebuilt zipped DLL.

**Comment by 57op** [comment]
Hello,
double check that your compiler is for 64 bit machines (e.g. MinGW-w64; I use the ones provided by https://www.winlibs.com/).

Anyway, you're right, the README page isn't clear enough on what actually do; compilation is not required, but recommended :)!
Pre-built DLLs are only provided for convenience.

If you want to try again to compile, let me know how it goes. I'll keep this issue open in case you meet other errors, so report them back here if need be.

Sooner or later, I will update README to be clearer;
thanks for reporting this issue.

**Comment by talzahr** [comment]
Success! From that link used `GCC 12.2.0 + LLVM/Clang/LLD/LLDB 14.0.6 + MinGW-w64 10.0.0 (UCRT) - release 2`

Thanks for your help!
