### ISSUE TITLE
Crash with v0.0.5 and mpv v0.34.0

### ISSUE THREAD

**Issue by francwalter** [57op/simple-mpv-webui-windows-libs#7]
Hello
as in #4 stated, again mpv.exe crashes when I use the acutal version 0.0.5 with mpv 0.34
And if I dont use the lua51.dll but an older one, I get some Assertion error in Line 208 of Expression ctx from mpv.exe and lua.c
So I still use the old 0.0.2, working without errors even with actual mpv.exe 0.34
frank

EDIT: last working version without mpv.exe crash is 0.0.3

**Comment by 57op** [comment]
Hi Frank,
is there a specific reason you want to use mpv 0.34?

I'm currently using 0.0.5 on the latest shinchiro build (0.35.0-221-ga40958cd) and it just works fine

**Comment by francwalter** [comment]
Hi I thought this is last version!
I used the updater.bat and it gives me the 0.34
Sorry, I will try that 0.35 then...
... You are absolutely right, with mpv v0.35 there is no crash, thank!
I took the [binary from Sourceforge](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230212-git-a40958c.7z/), from Shinshiro, as you proposed :)
I hope the included updater.bat will give me in the future these [binaries ](https://sourceforge.net/projects/mpv-player-windows/files/64bit/)too.
Thank!

**Comment by 57op** [comment]
very good! closing this issue then :)

notice that if you have a more recent CPU, you could also use 64bit-v3 releases.
shinchiro builds are the only one I'm going to support within this project, since I basically use the same lua package as his project goes on

thank you as always for reporting!
